using System.Net;
using System.Text;
using Codehard.Functional.AspNetCore.Shared;

namespace Codehard.Functional.AspNetCore.Sources;

internal static class OptionSource
{
    public static string FileName = "OptionExtensions.g.cs";

    public static string Generate()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using LanguageExt;");
        sb.AppendLine();
        sb.AppendLine($"namespace {Constants.Namespace};");
        sb.AppendLine();
        sb.AppendLine("public static class OptionExtensions");
        sb.Append("{");

        var type = typeof(HttpStatusCode);

        var statusCodes =
            Enum.GetValues(type)
                .Cast<HttpStatusCode>()
                .Distinct()
                .Select(s => Enum.GetName(type, s))
                .ToArray();

        foreach (var statusCode in statusCodes)
        {
            sb.AppendLine();
            sb.AppendLine(
                $"    public static Aff<A> ToAffWithFailTo{statusCode}<A>(this Option<A> ma, string errorMessage = \"\")");
            sb.AppendLine($"        => ma.ToAff().MapFailTo{statusCode}(errorMessage);");
        }
        
        foreach (var statusCode in statusCodes)
        {
            sb.AppendLine();
            sb.AppendLine(
                $"    public static Eff<A> ToEffWithFailTo{statusCode}<A>(this Option<A> ma, string errorMessage = \"\")");
            sb.AppendLine($"        => ma.ToEff().MapFailTo{statusCode}(errorMessage);");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}