using System.Net;
using System.Text;
using Codehard.Functional.AspNetCore.Shared;

namespace Codehard.Functional.AspNetCore.Sources;

internal static class TaskSource
{
    public static string FileName = "TaskExtensions.g.cs";

    public static string Generate()
    {
        var type = typeof(HttpStatusCode);

        var statusCodes =
            Enum.GetValues(type)
                .Cast<HttpStatusCode>()
                .Distinct()
                .Select(s => Enum.GetName(type, s))
                .ToArray();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using LanguageExt;");
        sb.AppendLine("using LanguageExt.Common;");
        sb.AppendLine();
        sb.AppendLine($"namespace {Constants.Namespace};");
        sb.AppendLine();
        sb.AppendLine("public static class TaskExtensions");
        sb.Append("{");

        foreach (var status in statusCodes)
        {
            sb.AppendLine();
            sb.AppendLine(
                $"    public static Aff<A> ToAffWithFailTo{status}<A>(this Task<A> ma, string message = \"\")");
            sb.AppendLine(
                $"        => ma.ToAff().MapFailTo{status}(message);");
        }

        foreach (var status in statusCodes)
        {
            sb.AppendLine();
            sb.AppendLine(
                $"    public static Aff<A> ToAffWithFailTo{status}<A>(this ValueTask<A> ma, string message = \"\")");
            sb.AppendLine(
                $"        => ma.ToAff().MapFailTo{status}(message);");
        }

        foreach (var status in statusCodes)
        {
            sb.AppendLine();
            sb.AppendLine(
                $"    public static Aff<Option<A>> ToAffOptionWithFailTo{status}<A>(this Task<A?> ma, string message = \"\")");
            sb.AppendLine(
                $"        => ma.ToAffOption().MapFailTo{status}(message);");
        }

        foreach (var status in statusCodes)
        {
            sb.AppendLine();
            sb.AppendLine(
                $"    public static Aff<Option<A>> ToAffOptionWithFailTo{status}<A>(this ValueTask<A?> ma, string message = \"\")");
            sb.AppendLine(
                $"        => ma.ToAffOption().MapFailTo{status}(message);");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}