// <auto-generated />
using System;
using Infrastructure.Test;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Test.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20230301064917_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Test.Entities.ChildModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid?>("MyModelId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("valueOpt")
                        .HasColumnType("numeric")
                        .HasColumnName("ValueOpt");

                    b.HasKey("Id");

                    b.HasIndex("MyModelId");

                    b.ToTable("ChildModel");
                });

            modelBuilder.Entity("Infrastructure.Test.Entities.MyModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("x")
                        .HasColumnType("integer")
                        .HasColumnName("Number");

                    b.Property<string>("y")
                        .HasColumnType("text")
                        .HasColumnName("Text");

                    b.HasKey("Id");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Infrastructure.Test.Entities.ChildModel", b =>
                {
                    b.HasOne("Infrastructure.Test.Entities.MyModel", null)
                        .WithMany("Childs")
                        .HasForeignKey("MyModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Infrastructure.Test.Entities.MyModel", b =>
                {
                    b.OwnsOne("Infrastructure.Test.Entities.OwnedEntity", "OwnedTestEntity", b1 =>
                        {
                            b1.Property<Guid>("MyModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value1")
                                .HasColumnType("text");

                            b1.Property<int?>("value2")
                                .HasColumnType("integer")
                                .HasColumnName("OwnedTestEntity_Value2");

                            b1.HasKey("MyModelId");

                            b1.ToTable("Models");

                            b1.WithOwner()
                                .HasForeignKey("MyModelId");
                        });

                    b.Navigation("OwnedTestEntity")
                        .IsRequired();
                });

            modelBuilder.Entity("Infrastructure.Test.Entities.MyModel", b =>
                {
                    b.Navigation("Childs");
                });
#pragma warning restore 612, 618
        }
    }
}
