using System.Linq;
using System.Text;

namespace Codehard.DomainModel.Generator.Extensions;

internal static class DefinitionExtensions
{
    public static StringBuilder AppendAutoGenerated(this StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");

        return sb;
    }

    public static StringBuilder AppendNamespace(this StringBuilder sb, DomainEntityDefinition entityDefinition)
    {
        if (!string.IsNullOrWhiteSpace(entityDefinition.Namespace))
        {
            sb.AppendLine($"namespace {entityDefinition.Namespace};");
            sb.AppendLine();
        }

        return sb;
    }

    public static StringBuilder AppendUsings(this StringBuilder sb, DomainEntityDefinition entityDefinition)
    {
        foreach (var @using in entityDefinition.Usings)
        {
            sb.AppendLine($"using {@using};");
        }

        return sb;
    }

    public static StringBuilder AppendSpecifications(
        this StringBuilder sb,
        DomainEntityDefinition entityDefinition)
    {
        foreach (var specification in entityDefinition.SpecificationDefinitions)
        {
            sb.AppendSpecification(entityDefinition, specification);
        }

        return sb;
    }

    private static StringBuilder AppendSpecification(
        this StringBuilder sb,
        DomainEntityDefinition entityDefinition,
        SpecificationDefinition specification)
    {
        var specificationName = $"{specification.Name}Specification";

        sb.AppendLine(
            $"    public partial class {specificationName} : ExpressionSpecification<{entityDefinition.EntityName}>");
        sb.AppendLine("    {");
        sb.Append($"        public {specificationName}(");

        if (specification.Arguments.Count == 0)
        {
            sb.AppendLine(")");
        }
        else if (specification.Arguments.Count == 1)
        {
            var arg = specification.Arguments.Single();
            sb.AppendLine($"{arg.Type} {arg.Name})");
        }
        else
        {
            sb.AppendLine();

            for (var index = 0; index < specification.Arguments.Count; index++)
            {
                var argument = specification.Arguments.ElementAt(index);

                sb.Append($"            {argument.Type} {argument.Name}");

                if (index != specification.Arguments.Count - 1)
                {
                    sb.AppendLine(",");
                }
            }

            sb.AppendLine(")");
        }

        sb.AppendLine($"            : base({specification.ExpressionText})");
        sb.AppendLine("        {");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine();

        return sb;
    }
}