using System.Linq;
using System.Text;
using Codehard.DomainModel.Generator.Extensions;

namespace Codehard.DomainModel.Generator.Sources;

internal static class SpecificationSource
{
    public static string GenerateSpecifications(this DomainEntityDefinition entityDefinition)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using Codehard.Common.DomainModel;");
        sb.AppendLine("using Codehard.Infrastructure.EntityFramework;");
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(entityDefinition.Namespace))
        {
            sb.AppendLine($"namespace {entityDefinition.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine(
            $"partial class {entityDefinition.EntityName}");
        sb.AppendLine("{");

        foreach (var specification in entityDefinition.SpecificationDefinitions)
        {
            sb.AppendSpecification(entityDefinition, specification);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}