// <auto-generated/>
namespace Codehard.Functional.AspNetCore;

public static class EffectExtensions
{
    public static Eff<A> MapFailToOK<A>(this Eff<A> ma, string message = "")
        => ma.MapToHttpResultError((int)HttpStatusCode.OK, message);

    public static Eff<A> MapFailToOK<A>(this Eff<A> ma, Func<Error, string> messageFunc)
        => ma.MapToHttpResultError((int)HttpStatusCode.OK, messageFunc);


    public static Eff<A> MapFailToCreated<A>(this Eff<A> ma, string message = "")
        => ma.MapToHttpResultError((int)HttpStatusCode.Created, message);

    public static Eff<A> MapFailToCreated<A>(this Eff<A> ma, Func<Error, string> messageFunc)
        => ma.MapToHttpResultError((int)HttpStatusCode.Created, messageFunc);


    public static Eff<A> MapFailToAccepted<A>(this Eff<A> ma, string message = "")
        => ma.MapToHttpResultError((int)HttpStatusCode.Accepted, message);

    public static Eff<A> MapFailToAccepted<A>(this Eff<A> ma, Func<Error, string> messageFunc)
        => ma.MapToHttpResultError((int)HttpStatusCode.Accepted, messageFunc);


    public static Eff<A> MapFailToNoContent<A>(this Eff<A> ma, string message = "")
        => ma.MapToHttpResultError((int)HttpStatusCode.NoContent, message);

    public static Eff<A> MapFailToNoContent<A>(this Eff<A> ma, Func<Error, string> messageFunc)
        => ma.MapToHttpResultError((int)HttpStatusCode.NoContent, messageFunc);


    public static Eff<A> MapFailToBadRequest<A>(this Eff<A> ma, string message = "")
        => ma.MapToHttpResultError((int)HttpStatusCode.BadRequest, message);

    public static Eff<A> MapFailToBadRequest<A>(this Eff<A> ma, Func<Error, string> messageFunc)
        => ma.MapToHttpResultError((int)HttpStatusCode.BadRequest, messageFunc);


    public static Eff<A> MapFailToUnauthorized<A>(this Eff<A> ma, string message = "")
        => ma.MapToHttpResultError((int)HttpStatusCode.Unauthorized, message);

    public static Eff<A> MapFailToUnauthorized<A>(this Eff<A> ma, Func<Error, string> messageFunc)
        => ma.MapToHttpResultError((int)HttpStatusCode.Unauthorized, messageFunc);


    public static Eff<A> MapFailToForbidden<A>(this Eff<A> ma, string message = "")
        => ma.MapToHttpResultError((int)HttpStatusCode.Forbidden, message);

    public static Eff<A> MapFailToForbidden<A>(this Eff<A> ma, Func<Error, string> messageFunc)
        => ma.MapToHttpResultError((int)HttpStatusCode.Forbidden, messageFunc);


    public static Eff<A> MapFailToNotFound<A>(this Eff<A> ma, string message = "")
        => ma.MapToHttpResultError((int)HttpStatusCode.NotFound, message);

    public static Eff<A> MapFailToNotFound<A>(this Eff<A> ma, Func<Error, string> messageFunc)
        => ma.MapToHttpResultError((int)HttpStatusCode.NotFound, messageFunc);


    public static Eff<A> MapFailToConflict<A>(this Eff<A> ma, string message = "")
        => ma.MapToHttpResultError((int)HttpStatusCode.Conflict, message);

    public static Eff<A> MapFailToConflict<A>(this Eff<A> ma, Func<Error, string> messageFunc)
        => ma.MapToHttpResultError((int)HttpStatusCode.Conflict, messageFunc);


    public static Eff<A> MapFailToUnprocessableEntity<A>(this Eff<A> ma, string message = "")
        => ma.MapToHttpResultError((int)HttpStatusCode.UnprocessableEntity, message);

    public static Eff<A> MapFailToUnprocessableEntity<A>(this Eff<A> ma, Func<Error, string> messageFunc)
        => ma.MapToHttpResultError((int)HttpStatusCode.UnprocessableEntity, messageFunc);


    public static Eff<A> MapFailToLocked<A>(this Eff<A> ma, string message = "")
        => ma.MapToHttpResultError((int)HttpStatusCode.Locked, message);

    public static Eff<A> MapFailToLocked<A>(this Eff<A> ma, Func<Error, string> messageFunc)
        => ma.MapToHttpResultError((int)HttpStatusCode.Locked, messageFunc);


    public static Eff<A> MapFailToInternalServerError<A>(this Eff<A> ma, string message = "")
        => ma.MapToHttpResultError((int)HttpStatusCode.InternalServerError, message);

    public static Eff<A> MapFailToInternalServerError<A>(this Eff<A> ma, Func<Error, string> messageFunc)
        => ma.MapToHttpResultError((int)HttpStatusCode.InternalServerError, messageFunc);
}