// <auto-generated/>
using LanguageExt.Common;

namespace Codehard.Functional.AspNetCore;

public static class GuardExtensions
{
    public static Guard<Error, Unit> GuardWithHttpStatus(bool flag, HttpStatusCode httpStatusCode, string message = "")
    {
        return guard<Error>(flag, Error.New((int)httpStatusCode, message));
    }

    public static Guard<Error, Unit> GuardWithOK(bool flag, string message = "")
        => GuardWithHttpStatus(flag, HttpStatusCode.OK, message);

    public static Guard<Error, Unit> GuardWithCreated(bool flag, string message = "")
        => GuardWithHttpStatus(flag, HttpStatusCode.Created, message);

    public static Guard<Error, Unit> GuardWithAccepted(bool flag, string message = "")
        => GuardWithHttpStatus(flag, HttpStatusCode.Accepted, message);

    public static Guard<Error, Unit> GuardWithNoContent(bool flag, string message = "")
        => GuardWithHttpStatus(flag, HttpStatusCode.NoContent, message);

    public static Guard<Error, Unit> GuardWithBadRequest(bool flag, string message = "")
        => GuardWithHttpStatus(flag, HttpStatusCode.BadRequest, message);

    public static Guard<Error, Unit> GuardWithUnauthorized(bool flag, string message = "")
        => GuardWithHttpStatus(flag, HttpStatusCode.Unauthorized, message);

    public static Guard<Error, Unit> GuardWithForbidden(bool flag, string message = "")
        => GuardWithHttpStatus(flag, HttpStatusCode.Forbidden, message);

    public static Guard<Error, Unit> GuardWithNotFound(bool flag, string message = "")
        => GuardWithHttpStatus(flag, HttpStatusCode.NotFound, message);

    public static Guard<Error, Unit> GuardWithConflict(bool flag, string message = "")
        => GuardWithHttpStatus(flag, HttpStatusCode.Conflict, message);

    public static Guard<Error, Unit> GuardWithUnprocessableEntity(bool flag, string message = "")
        => GuardWithHttpStatus(flag, HttpStatusCode.UnprocessableEntity, message);

    public static Guard<Error, Unit> GuardWithLocked(bool flag, string message = "")
        => GuardWithHttpStatus(flag, HttpStatusCode.Locked, message);

    public static Guard<Error, Unit> GuardWithInternalServerError(bool flag, string message = "")
        => GuardWithHttpStatus(flag, HttpStatusCode.InternalServerError, message);
}