// <auto-generated/>
namespace Codehard.Functional.AspNetCore;

public static class OptionExtensions
{
    public static Eff<A> ToEffWithFailToOK<A>(this Option<A> ma, string errorMessage = "")
        => ma.ToEff().MapFailToOK(errorMessage);

    public static Eff<A> ToEffWithFailToCreated<A>(this Option<A> ma, string errorMessage = "")
        => ma.ToEff().MapFailToCreated(errorMessage);

    public static Eff<A> ToEffWithFailToAccepted<A>(this Option<A> ma, string errorMessage = "")
        => ma.ToEff().MapFailToAccepted(errorMessage);

    public static Eff<A> ToEffWithFailToNoContent<A>(this Option<A> ma, string errorMessage = "")
        => ma.ToEff().MapFailToNoContent(errorMessage);

    public static Eff<A> ToEffWithFailToBadRequest<A>(this Option<A> ma, string errorMessage = "")
        => ma.ToEff().MapFailToBadRequest(errorMessage);

    public static Eff<A> ToEffWithFailToUnauthorized<A>(this Option<A> ma, string errorMessage = "")
        => ma.ToEff().MapFailToUnauthorized(errorMessage);

    public static Eff<A> ToEffWithFailToForbidden<A>(this Option<A> ma, string errorMessage = "")
        => ma.ToEff().MapFailToForbidden(errorMessage);

    public static Eff<A> ToEffWithFailToNotFound<A>(this Option<A> ma, string errorMessage = "")
        => ma.ToEff().MapFailToNotFound(errorMessage);

    public static Eff<A> ToEffWithFailToConflict<A>(this Option<A> ma, string errorMessage = "")
        => ma.ToEff().MapFailToConflict(errorMessage);

    public static Eff<A> ToEffWithFailToUnprocessableEntity<A>(this Option<A> ma, string errorMessage = "")
        => ma.ToEff().MapFailToUnprocessableEntity(errorMessage);

    public static Eff<A> ToEffWithFailToLocked<A>(this Option<A> ma, string errorMessage = "")
        => ma.ToEff().MapFailToLocked(errorMessage);

    public static Eff<A> ToEffWithFailToInternalServerError<A>(this Option<A> ma, string errorMessage = "")
        => ma.ToEff().MapFailToInternalServerError(errorMessage);
}